MODEL:
  WEIGHTS: "pretrained_models/yolox_l.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  META_ARCHITECTURE: "YOLOX"
  BACKBONE:
    NAME: "build_yolopafpn_backbone"
  ROI_HEADS:
    NAME: "YOLOXHead"
  YOLOX:
    DEPTH: 1.0
    WIDTH: 1.0
    DEPTHWISE: False
    NUM_CLASSES: 1
  SCPDARKNET:
    OUT_FEATURES: ["dark3", "dark4", "dark5"]
  YOLOPAFPN:
    IN_FEATURES: ["dark3", "dark4", "dark5"]
    IN_CHANNELS: [256, 512, 1024]
    OUT_FEATURES: ["p3", "p4", "p5"]
  ROI_YOLO_HEAD:
    STRIDES: [8, 16, 32]
    IN_FEATURES: ["p3", "p4", "p5"]
DATASETS:
  TRAIN: ("MOT17_train",)
  TEST: ("MOT17_val",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
  WARMUP_ITERS: 1000
  STEPS: (12000, 16000)
  MAX_ITER: 20000
VERSION: 2