MODEL:
  WEIGHTS: "pretrained_models/yolox_m.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  META_ARCHITECTURE: "YOLOX"
  BACKBONE:
    NAME: "build_yolopafpn_backbone"
  ROI_HEADS:
    NAME: "YOLOXHead"
  YOLOX:
    DEPTH: 0.67
    WIDTH: 0.75
  SCPDARKNET:
    OUT_FEATURES: ["dark3", "dark4", "dark5"]
    DEPTHWISE: True
  YOLOPAFPN:
    IN_FEATURES: ["dark3", "dark4", "dark5"]
    IN_CHANNELS: [256, 512, 1024]
    OUT_FEATURES: ["p3", "p4", "p5"]
  ROI_YOLO_HEAD:
    NUM_CLASSES: 1
    STRIDES: [8, 16, 32]
    IN_FEATURES: ["p3", "p4", "p5"]
    DEPTHWISE: True
DATASETS:
  TRAIN: ("MOT17_train",)
  TEST: ("MOT17_val",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.002
  WARMUP_ITERS: 1000
  STEPS: (6000, 8000)
  MAX_ITER: 10000
VERSION: 2